{% set version = "0.4.2" %}
{% set sha256 = "8a5cf9bfa21782db14307aca5503a3ecc8657aba0d75078a17f5561e07e001f4" %}

package:
  name: damageprofiler
  version: '{{version}}'

source:
  url: https://github.com/Integrative-Transcriptomics/DamageProfiler/releases/download/v{{version}}/DamageProfiler-{{version}}.jar
  sha256: '{{sha256}}'

build:
  noarch: generic
  number: 1

requirements:
  run:
    - openjdk
    - python

test:
  commands:
    - damageprofiler -h  >/dev/null

about:
  home: https://github.com/Integrative-Transcriptomics/DamageProfiler
  license: GPL-3.0
  license_family: GPL
  summary: A Java based tool to determine damage patterns on ancient DNA as a replacement for mapDamage
