package:
  name: metabat2
  version: "2.12.1"

source:
  url: https://bitbucket.org/berkeleylab/metabat/downloads/metabat-static-binary-linux-x64_v2.12.1.tar.gz
  md5: 4c8345ba5b3023b7b4cd16b38bd70c64

requirements:
  build:

  run:


test:
  commands:
    - 'metabat2 -h | grep "MetaBAT: Metagenome Binning based" > /dev/null'

about:
  home: https://bitbucket.org/berkeleylab/metabat
  license_file: license.txt
  summary: "MetaBAT2 is a program for binning metagenome-assembled contigs into bins/MAGs."


