{% set name = "BBMap" %}
{% set version = "38.34" %}
{% set sha256 = "a7feb01dc383bc492c50f7b8d5bf4c60aee09918dd6dbeddde0e8e81e51a327a" %}

build:
  number: 0

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://downloads.sourceforge.net/project/{{ name|lower }}/{{ name }}_{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - openjdk >=7.0
    - {{ compiler('c') }}
    
  run:
    - openjdk >=7.0

test:
  files:
    - test.fa
    - testdatabase.fa
    - testexpected.sam
  commands:
    - bbmap.sh --version 2>&1 | grep "BBMap version {{ version }}"
    - bbmerge.sh --version 2>&1 | grep "BBMap version {{ version }}"
    - bbduk.sh --version 2>&1 | grep "BBMap version {{ version }}"
    - bbmask.sh --version 2>&1 | grep "BBMap version {{ version }}"
    - bbnorm.sh --version 2>&1 | grep "BBMap version {{ version }}"
    - bbmap.sh | grep "BBMap"
    - bbmerge.sh | grep "BBMerge"
    - bbduk.sh | grep "BBDuk"
    - bbmask.sh | grep "BBMask"
    - bbnorm.sh | grep "BBNorm"

about:
  home: https://sourceforge.net/projects/bbmap
  doc_url: https://jgi.doe.gov/data-and-tools/bbtools/bb-tools-user-guide/
  license: "UC-LBL license (see package)"
  license_file: license.txt
  summary: "BBMap is a short read aligner, as well as various other bioinformatic tools."

extra:
  notes: |
    BBMap is a series of Java programs, but they come with a number of custom
    wrapper shell scripts. Each of these is symlinked to the conda bin directory
    during install.
  identifiers:
    - biotools:bbmap
    - doi:10.1371/journal.pone.0185056
  recipe-maintainers:
    - notestaff


