{% set version = "1.0.0" %}

package:
  name: bwise
  version: '{{version}}'

source:
  url: "https://github.com/Malfoy/BWISE/archive/1.0.0.tar.gz"
  sha256: daca421f91e9b3a4c272b46665df2e681d0068bb53fde86f41f04a2637f4f91d

build:
  number: 1
  skip: True # [osx or py26]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  run:
    - python >2.7
    - bgreat
    - bcalm
    - btrim

test:
  commands:
    - bwise

about:
  home: https://github.com/Malfoy/BWISE
  license: AGPL-3.0
  # license_file: MISSING!
  summary: |
    BWISE is a de Bruijn assembly workflow using integral information of 
    short paired-end reads
