package:
  name: pybel
  version: "0.12.2"

source:
  url: https://files.pythonhosted.org/packages/3b/f1/6eb89d5011886525804d03a1915f74e66c80efb651964a992df13be241f1/PyBEL-0.12.2.tar.gz
  sha256: 178e32abac2bdd241d17e9f46b0c364e3472e7a0329a5fd402e419990b6bc408

build:
  entry_points:
    - pybel = pybel.cli:main
  number: 0
  # tests fail on osx: https://travis-ci.org/bioconda/bioconda-recipes/jobs/235726973#L3656
  # click needs to be patched in order to properly detect unicode in py3k
  skip: true  # [osx or py3k]

requirements:
  host:
    - python
    - setuptools
    - requests
    - ndex-python
    - requests-file
    - networkx
    - pyparsing
    - configparser  # [py27]
    - py2neo
    - click
    - sqlalchemy
    - onto2nx
  run:
    - python
    - requests
    - ndex-python
    - requests-file
    - networkx
    - pyparsing
    - configparser  # [py27]
    - py2neo
    - click
    - sqlalchemy
    - onto2nx

test:
  # Python imports
  imports:
    - pybel
    - pybel.ext
    - pybel.manager
    - pybel.parser
    - pybel.parser.modifiers
  commands:
    # click requires a unicode locale
    - LANG=C.UTF-8 pybel --help

about:
  home: https://github.com/pybel/pybel
  license: Apache Software License
  summary: 'PyBEL is a Python package for parsing and handling biological networks encoded in the Biological Expression Language (BEL)'
