package:
  name: rvtests 
  version: "2.0.6"

build:
  number: 1

source:
  url: https://github.com/zhanxw/rvtests/archive/v2.0.6.tar.gz
  sha256: 72f4419d5d3dd73b8eb58f7ffaabf19a41c99f968ecde9611f9b76f74acc0743

requirements:
  build:
    - {{ compiler('cxx') }}
    - wget
    - zlib
  host:
    - wget # [not osx]
    - curl # [osx]
    - zlib
  run:
    - wget # [not osx]

test:
  commands:
    - set 
    - rvtests --help 

about:
  home: https://github.com/zhanxw/rvtests
  license: GPL
  license_file: LICENSE
  summary: Rare variant test software for next generation sequencing data

extra:
  identifiers:
    - doi:10.1093/bioinformatics/btw079
    - biotools:rvtests
