package:
  name: rvtests 
  version: "20181121"

build:
  number: 1

source:
  url: https://github.com/zhanxw/rvtests/archive/v2.0.6.tar.gz
  sha256: 72f4419d5d3dd73b8eb58f7ffaabf19a41c99f968ecde9611f9b76f74acc0743

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - openblas # [not osx]
  run:
    - openblas # [not osx]

test:
  commands:
    - rvtests --help 

about:
  home: https://github.com/zhanxw/rvtests
  license: GPL
  license_file: LICENSE
  summary: Rare variant test software for next generation sequencing data
