{% set version = "1.2.0rc" %}

package:
  name: r-biodb
  version: '{{ version }}'

source:
  url: 'https://github.com/pkrog/biodb/archive/v{{ version }}.tar.gz'
  sha256: 1f92247d4f4347b13307a2161e33adfb4bd49efaff7262d61aabc2b91f9ee21e

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - r-base
    - r-codetools
    - r-devtools
    - r-rcpp
    - r-xml
    - r-stringr
    - r-plyr
    - r-bitops
    - r-rcurl
    - r-r.utils
  run:
    - r-base
    - r-rcpp
    - r-xml
    - r-stringr
    - r-plyr
    - r-bitops
    - r-rcurl
    - r-r.utils
    - r-jsonlite
    - r-digest

test:
  commands:
    - $R -e "library(biodb)"
    - $R -e "library(biodb) ; biodb = biodb::Biodb()"

about:
  license: AGPL-3.0
  summary: 'An R package for connecting to chemical and biological databases.'
  home: https://github.com/pkrog/biodb
extra:
  recipe-maintainers:
      - pkrog
      - MathiasHaudgaard
      - FrodePedersen
      - ArneKr
      - johanneskoester
      - bgruening
      - daler
      - jdblischak
