{% set version="1.3.0.20181210190634" %}
package:
  name: arvados-cwl-runner
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/arvados-cwl-runner/arvados-cwl-runner-{{ version }}.tar.gz
  sha256: 44b4da4646b1908e0e00011ceb3c7f45e47fb5710aa7bfa57126d72b7c1c9f6e

build:
  number: 0
  skip: True # [not py27]

requirements:
  host:
    - python
    - setuptools
    - ruamel.yaml >=0.13.7,<0.15
    - cwltool >=1.0.20180130110340
    - schema-salad >=2.6.20171201034858
    - arvados-python-client >=0.1.20171211211613

  run:
    - python
    - ruamel.yaml >=0.13.7,<0.15
    - cwltool >=1.0.20180130110340
    - schema-salad >=2.6.20171201034858
    - arvados-python-client >=0.1.20171211211613

test:
  imports:
    - arvados_cwl

  # Needs connection to Arvados server to run help
  #commands:
  #  - arvados-cwl-runner --help

about:
  home: https://github.com/curoverse/arvados/tree/master/sdk/cwl
  license: Apache 2.0
  summary: 'Arvados Common Workflow Language runner'
