{% set version = "3.0.3" %}

package:
  name: mixcr
  version: {{ version }}

source:
  url: https://github.com/milaboratory/mixcr/releases/download/v{{ version }}/mixcr-{{ version }}.zip
  sha256: a969d815f8e7a8c3ffe082fdfe8f63cadbef7820b9299d648a454fe9480c72af

build:
  number: 0
  noarch: generic

requirements:
  run:
    - openjdk

test:
  commands:
    - mixcr help

about:
  home: https://github.com/milaboratory/mixcr
  license: https://github.com/milaboratory/mixcr/blob/develop/LICENSE
  summary: >
    MiXCR is a universal software for fast and accurate analysis of
    raw T- or B- cell receptor repertoire sequencing data.
