{% set version="1.0.20181118133959" %}

package:
  name: cwltool
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cwltool/cwltool-{{ version }}.tar.gz
  sha256: 13d23445f86a45685e4ee9dc6b69caffd7058e265f8e2185fec330ba9c7fe1aa

build:
  noarch: python
  number: 0

requirements:
  host:
    - python
    - setuptools
    - requests
    - shellescape
    - cwltest >=1.0.20180209171722
    # schema-salad and pinned deps
    - schema-salad >=2.6.20170927145003,<3.0
    - cachecontrol >=0.11.7,<0.12
    - mistune >=0.7.3,<0.8
    - rdflib >=4.2.2
    - rdflib-jsonld >=0.3.0
    - ruamel.yaml >=0.12.4,<0.15
    - typing >=3.5.3,<3.6

  run:
    - python
    - requests
    - shellescape
    - cwltest >=1.0.20180209171722
    # schema-salad and pinned deps
    - schema-salad >=2.6.20170927145003,<3.0
    - cachecontrol >=0.11.7,<0.12
    - mistune >=0.7.3,<0.8
    - rdflib >=4.2.2
    - rdflib-jsonld >=0.3.0
    - ruamel.yaml >=0.12.4,<0.15
    - typing >=3.5.3,<3.6

test:
  imports:
    - cwltool
  commands:
    - cwltool --help

about:
  home: https://github.com/common-workflow-language/cwltool
  license: Apache License 2.0
  summary: Common Workflow Language reference implementation
