package:
  name: segway
  version: "2.0.3"

source:
  url: https://files.pythonhosted.org/packages/76/95/4beac9675284edac172c23bcde6ea3e5e741f110c86f22eb16560b3d2ff0/segway-2.0.3.tar.gz
  sha256: b2f2c97e0ff9d064b8271554e60e954764354d04237876766e55e4e484cbb547

build:
  preserve_egg_dir: True
  number: 0
  entry_points:
    - segway = segway.run:main
    - segway-task = segway.task:main
    - segway-layer = segway.layer:main
    - segway-winner = segway.winner:main

requirements:
  host:
    - python
    - setuptools
    - genomedata >1.4.2
    - autolog >=0.2.0
    - textinput >=0.2.0
    - optbuild >=0.2.0
    - optplus >=0.2.0
    - pytables >=2.0.4
    - numpy
    - path.py >=11
    - colorbrewer >=0.2.
    - drmaa >=0.4a3
    - six
    - hgtools
    - gmtk
    - ucsc-bedtobigbed

  run:    
    - python
    - setuptools
    - genomedata >1.4.2
    - autolog >=0.2.0
    - textinput >=0.2.0
    - optbuild >=0.2.0
    - optplus >=0.2.0
    - pytables >=2.0.4
    - numpy
    - path.py >=11
    - colorbrewer >=0.2.
    - drmaa >=0.4a3
    - six
    - hgtools
    - gmtk
    - ucsc-bedtobigbed

test:
  imports:
    - segway

  commands:
    - segway --help

about:
  home: http://segway.hoffmanlab.org/
  license: GPL2
  summary: 'a tool for easy pattern discovery and identification in functional genomics data.'

extra:
  identifiers:
    - doi:10.1093/bioinformatics/btx603
    - biotools:segway
