package:
  name: vcflib
  version: '1.0.0_rc2'

source:
  url: https://github.com/vcflib/vcflib/archive/v1.0.0-rc2.tar.gz
  md5: 465777c9ff06093a964c9791ff7ba4cd

build:
  number: 0
  skip: True  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - zlib
    - bzip2
    - xz

test:
  commands:
    - vcfallelicprimitives -h

about:
  home: https://github.com/ekg/vcflib
  license: MIT
  summary: Command-line tools for manipulating VCF files

extra:
  identifiers:
    - biotools:vcflib
    - doi:10.1101/023754
