{% set version = '1.1-22' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gap
  version: {{ version|replace("-", "_") }}

source:

  url:
    - {{ cran_mirror }}/src/contrib/gap_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gap/gap_{{ version }}.tar.gz
  sha256: 71a691aac9ce29bfcf1159eacba1866c8571b781f68fb32a3e52fb8584f03ef7

build:
  merge_build_host: True  # [win]

  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('gap')"           # [not win]
    - "\"%R%\" -e \"library('gap')\""  # [win]

about:
  home: https://jinghuazhao.github.io
  license: GPL (>= 2)
  summary: It is designed as an integrated package for genetic data analysis of both population
    and family data. Currently, it contains functions for sample size calculations of
    both population-based and family-based designs, probability of familial disease
    aggregation, kinship calculation, statistics in linkage analysis, and association
    analysis involving genetic markers including haplotype analysis with or without
    environmental covariates.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}\/lib\/R\/share\/licenses\/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]
  license_file: '{{ environ["PREFIX"] }}\/lib\/R\/share\/licenses\/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]
extra:
  recipe-maintainers:
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
extra:
  recipe-maintainers:
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
