{% set name = "cyvcf2" %}
{% set version = "0.10.4" %}
{% set sha256hash = "32d97a5c480e3f47732591d37ce76ed23b99e6c7f2c8ef0a874b7c1dec5ea571" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brentp/cyvcf2/archive/v{{ version }}.tar.gz
  sha256: {{ sha256hash }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - cython
    - numpy
    - zlib
    - libcurl

  run:
    - python
    - numpy
    - zlib
    - coloredlogs
    - click
    - libcurl

test:
  imports:
    - cyvcf2

about:
  home: https://github.com/brentp/cyvcf2
  summary: A cython wrapper around htslib built for fast parsing of Variant Call Format (VCF) files
  license: MIT
