{% set name = "perl-dbd-mysql" %}
{% set version = "4.049" %}
{% set sha256 = "cfbf020f1e53a1d9d48ab964af1e3fa0228dc4f5df6da66e691c5c01cae0413b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/D/DV/DVEEDEN/DBD-mysql-4.049.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}

  host:
    - perl
    - perl-time-hires
    - perl-test-simple
    - perl-dbi
    - perl-test-deep
    - perl-data-dumper
    - perl-extutils-makemaker
    - mysql-connector-c

  run:
    - perl
    - perl-dbi
    - mysql-connector-c

test:
  imports:
    - DBD::mysql

about:
  home: http://dbi.perl.org/
  license: perl_5
  summary: 'A MySQL driver for the Perl5 Database Interface (DBI)'

extra:
  identifiers:
    - biotools:dbd
    - doi:10.1093/nar/gkm964
